# Generated by Django 5.2 on 2025-10-27 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        # Code fully generated by ChatGPT
        # Explained by human:
        # - Create another colum to store tsvector of description
        # - Create GIN index for this tsvector field for easy searching
        # - Search using this tsvector fields ONLY, avoid searching by description
        migrations.RunSQL(
            """
            ALTER TABLE products_product
            ADD COLUMN description_tsv tsvector
            GENERATED ALWAYS AS (to_tsvector('english', coalesce(description, ''))) STORED;
            """,
            "ALTER TABLE products_product DROP COLUMN description_tsv;"
        ),
        migrations.RunSQL(
            """
            CREATE INDEX product_description_tsv_gin
            ON products_product USING gin (description_tsv);
            """,
            "DROP INDEX product_description_tsv_gin;"
        ),
    ]
