# Generated by Django 5.2 on 2025-10-27 22:05

import django.contrib.postgres.search
from django.db import migrations, models
from django.db.migrations.operations.special import SeparateDatabaseAndState


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20251027_2027'),
    ]

    operations = [
        SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='product',
                    name='description_tsv',
                    field=models.GeneratedField(db_persist=True, expression=django.contrib.postgres.search.SearchVector('description', config='english'), null=True, output_field=django.contrib.postgres.search.SearchVectorField()),
                ),
            ],
            database_operations=[]
        )
    ]
