# Generated by Django 5.2 on 2025-10-27 21:06

from django.db import migrations
from django.contrib.postgres.search import SearchVectorField


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20251027_2027'),
    ]

    operations = [
        # Generated AI: Expose "description_tsv" to Product model without
        # recreating the field in the database
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="product",
                    name="description_tsv",
                    field=SearchVectorField(editable=False, null=True, db_column="description_tsv"),
                ),
            ],
            database_operations=[],  # important: no DB change
        )
    ]
